#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    #autocomplete_method = "coc"
    snippet_engine = "ultisnips"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    default_indent = 4
    bootstrap_before = "myspacevim#before"
    bootstrap_after= "myspacevim#after"
    project_rooter_patterns = ['.repo/', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']

[[layers]]
name = "autocomplete"
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "chinese"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "tmux"

[[layers]]
name = "git"

[[layers]]
name = "fzf"

[[layers]]
name = "sudo"

#[[layers]]
#name = "gtags"
#gtagslabel = "pygments"
#
#[[layers]]
#name = "cscope"

# ====================================================================

#[[layers]]
#name = "lsp"
#filetypes = [
#  "c",
#  "cpp",
#  "python"
#]
#[layers.override_cmd]
#c = ["clangd", "-j=12", "--all-scopes-completion", "--background-index=true", "--completion-style=detailed", "--cross-file-rename", "--function-arg-placeholders", "--header-insertion=never", "--pch-storage=disk"]
#cpp = ["clangd", "-j=12", "--all-scopes-completion", "--background-index=true", "--completion-style=detailed", "--cross-file-rename", "--function-arg-placeholders", "--header-insertion=never", "--pch-storage=disk"]

#[[layers]]
#name = "lang#python"

#[[layers]]
#name = "lang#java"

[[layers]]
name = "lang#sh"

#[[layers]]
#name = "lang#c"
#clang_executable = "/usr/bin/clang"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

# ====================================================================

[[custom_plugins]]
name="icymind/NeoSolarized"
merged = false

[[custom_plugins]]
name="junegunn/vim-easy-align"
merged = false

#[[custom_plugins]]
#repo = "rhysd/vim-clang-format"
#merged = false

